### ISSUE TITLE
`message_map` keys should be atoms

### ISSUE THREAD

**Issue by jchristgit** [Kraigie/nostrum#100]
The [docs for `Nostrum.Error.ApiError.message_map()`](https://kraigie.github.io/nostrum/Nostrum.Error.ApiError.html#t:message_map/0) specify that the map keys are atoms, but they are currently being returned as strings.

May be relevant: https://github.com/Kraigie/nostrum/blob/master/lib/nostrum/api/ratelimiter.ex#L167

**Comment by Kraigie** [comment]
resolved with d70760f5e52e92a876c1f73ae5a229dc7ff898c7
