### ISSUE TITLE
Message cache

### ISSUE THREAD

**Issue by jchristgit** [Kraigie/nostrum#101]
Nostrum currently caches guilds, channels, and users. I think that a message cache would prove useful to some bots. Some examples from mine:
- a mod log checking the message cache for deleted / edited messages
- searching past messages for something specific

This is not a common thing across bots, and having the message cache opt-in (maybe through another module) would be the best approach, since bots with a lot of channels will end up with very high memory usage.
As far as I'm aware, these are decent methods of caching messages:
- per-guild (cache max. *n* messages per guild before dropping old messages)
- per-channel (cache max. *n* messages per channel before dropping old messages)

I currently use an  `Agent` to accomplish caching on a per-channel basis: https://github.com/jchristgit/Bolt/blob/master/lib/bolt/message_cache.ex
It's very dumb but it does its job. An ETS table might be better suited, but I've never used ETS directly, so I wouldn't know ...

My question: is something like this planned for nostrum, would it be a "nice-to-have", or is the library supposed to keep the implementation of this up to the user?

**Comment by queer** [comment]
I can see this being a nice-to-have, tho it'd be nice to have the option to disable it for anyone who doesn't want message caching for w/e reason. But since most bots don't *need* it, I personally am not sure it makes sense to implement in the API lib itself. It might make more sense to have a repo of "Nostrum extensions" or something like that for things like this.

**Comment by Kraigie** [comment]
I can see a use case for something like this, but I'm hesitant to include something like this within the lib. Like you mentioned, creating your own cache with your own specific needs in mind will probably work out better in the end. 

I support @queer's suggestion of maybe providing something like an extensions lib that users can opt in to use!

**Comment by jchristgit** [comment]
Since this issue is nearing its first birthday and as you said an extensions lib would be better suited, I've implemented a message cache in the nosedrum library and I suppose that means I can close this issue
