### ISSUE TITLE
Example Consumer script won't post on discord channel?

### ISSUE THREAD

**Issue by Nixonite** [Kraigie/nostrum#109]
Hi all,

So I found this lib over the weekend and I was trying out the example consumer program. The bot is connected, sees when someone is typing, but when I write "!ping" in the general channel it says "message created" in the debug logs but I don't see a message on the channel.

Am I missing something obvious here? I granted all permissions to the bot to see if it worked (my example server that nobody uses so it's okay).

**Comment by Kraigie** [comment]
What does your function look like that you expect to be handling this?

Also for future reference, a question like this would probably be better suited for the discord channel. 😁

**Comment by Nixonite** [comment]
Oh sorry I'll ask there, forgot there's a channel for this stuff.
