### ISSUE TITLE
Re-implement the ability to define custom consumers

### ISSUE THREAD

**Issue by Kraigie** [Kraigie/nostrum#130]
Right now it's not possible to define customer consumers properly. You can see #126 for some discussion on the matter.

To properly implement this, if the config option is true, we should disable the cache supervisor as well as the gen_stage stages besides the producers. We might also want to consider creating a utility function so users can more easily subscribe to our producers, or mention the name of the producer somewhere in the docs.

**Comment by jchristgit** [comment]
Closing this. You can now implement "custom" consumers quite easily by simply joining the consumer group (see `Nostrum.ConsumerGroup`) and dealing with the events.
