### ISSUE TITLE
no function clause matching in Nostrum.Api.handle_request_with_decode/2 raised on `add_member_to_guild/3` function when member already exists

### ISSUE THREAD

**Issue by matthewheath** [Kraigie/nostrum#133]
I'm getting a `no function clause matching in Nostrum.Api.handle_request_with_decode/2` exception being raised on the `add_member_to_guild/3` function when that member already exists on the server.

The [Discord API docs](https://discordapp.com/developers/docs/resources/guild#add-guild-member) indicate that a 204 No Content status code is sent back in this scenario with an empty body. In this case, the function clause is being called with the following arguments:

1. {:ok}
2. {:struct, Nostrum.Struct.Guild.Member}

and the following function clauses were attempted:

`defp handle_request_with_decode({:error, _} = error, _type)`
`defp handle_request_with_decode({:ok, body}, type)`

The error is being raised at [line 2571](https://github.com/Kraigie/nostrum/blob/master/lib/nostrum/api.ex#L2571)

I've tried it on both the stable version `0.1` and the development version (currently on the development version) but the error persists in both. 😞

**Comment by Kraigie** [comment]
Should be fixed with 1065fd86758398674d14b667611ef9be80bafd60. For now you'll have to use the github version. 

Thanks for the report!
