### ISSUE TITLE
Update version guidance in Intro.md

### ISSUE THREAD

**Issue by inklesspen** [Kraigie/nostrum#135]
The Intro doc says to use the git master of nostrum, instead of a released version.

```markdown
The version of this library hosted on Hex is severely outdated. Once the dependency
[gun](https://github.com/ninenines/gun) has a 2.0 release, a new package will be
released with the most up to date Elixir version (1.6.4 as of the time of this writing).

In the meantime it is recommended you use the version hosted on GitHub.
```

However, the 0.3.0 release replaced gun with websockex. Is it still advised to use the dev version? Or can I use nostrum 0.3.2 without causing extra trouble for myself?

**Comment by jchristgit** [comment]
With https://github.com/Kraigie/nostrum/pull/136 merged, can this be closed?

**Comment by inklesspen** [comment]
Looks good to me, though I'd consider some mechanism to automatically update the version numbers in the docs when new versions are released.

**Comment by jchristgit** [comment]
Closing per #136 merged.
