### ISSUE TITLE
Documentation | Example

### ISSUE THREAD

**Issue by xp4u1** [Kraigie/nostrum#140]
The "more complex bot" called _mark-hoff_ doesn't exists anymore. Please update the documentation (it's the front-page).

**Comment by jchristgit** [comment]
Perhaps it would be nice to put a list of open source nostrum bots there? https://github.com/search?l=&p=1&q=nostrum+filename%3Amix.exs+language%3AElixir&ref=advsearch&type=Repositories&utf8=%E2%9C%93 turns up a few but there's probably more.
