### ISSUE TITLE
I'm getting randomly disconnected.

### ISSUE THREAD

**Issue by rikusen0335** [Kraigie/nostrum#149]
Well, I'm still getting these:
```
12:54:59.104 [warn]  websocket disconnected with reason {:remote, 1000, ""}, attempting reconnect

12:55:54.565 [warn]  websocket disconnected with reason {:remote, 1000, ""}, attempting reconnect

12:56:50.130 [warn]  websocket disconnected with reason {:remote, 1000, ""}, attempting reconnect

12:57:45.627 [warn]  websocket disconnected with reason {:remote, 1000, ""}, attempting reconnect

12:58:41.166 [warn]  websocket disconnected with reason {:remote, 1000, ""}, attempting reconnect

12:59:36.632 [warn]  websocket disconnected with reason {:remote, 1000, ""}, attempting reconnect
```

Any of I did like restart, remake, and different environment doesn't solve this issue.

Maybe this is similar to #132.

**Comment by rikusen0335** [comment]
So I got it randomly and it sometimes connect to. I can't understand what happened to me.

**Comment by SanksTheYokai** [comment]
Hello, @rikusen0335!

Known issue. This is a bug in the websocket library that nostrum uses. Updating to OPT 22 should fix the problem.

**Comment by rikusen0335** [comment]
Thank you for replying!
I already updated to OPT 22, and it wouldn't fix.

`elixir -v` results:
```
Erlang/OTP 22 [erts-10.4.1] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [hipe] 

Elixir 1.8.2 (compiled with Erlang/OTP 20)
```
and also I'm using WSL Ubuntu, but it also happens on my Manjaro Linux.

**Comment by Andris0** [comment]
I believe OTP 21.2 was the last version without this issue.
That is what I have been using and I have not had any signs of **_THE BUG._**

**Comment by rikusen0335** [comment]
Thank you for the information. I'll check it.

**Comment by rikusen0335** [comment]
I'd figured it! Recompile Elixir v1.9 is worked for me.
Thank you guys @SanksTheYokai @Andris0 so much.

**Comment by rikusen0335** [comment]
Sorry for asking again.
I just got disconnected after recompile/restarting. But it'll be connected to wait for minutes.
Did anyone get this?

**Comment by Kraigie** [comment]
Could you provide your elixir and otp version? And any relevant logs you think could help. 

I see you recompiled to elixir 1.9, but the issue was with the OTP version and as far as I know OTP and elixir version are pretty loosely coupled. You could be on an older version of OTP still!

**Comment by rikusen0335** [comment]
Thank you for replying.

Here's info:
`elixir -v`
```
Erlang/OTP 22 [erts-10.4.1] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [hipe]
Elixir 1.9.0-rc.0 (e5888e7) (compiled with Erlang/OTP 22)
```
and using nostrum v0.3.

**Comment by barkerja** [comment]
Seeing the same thing. On Elixir 1.9 OTP 22 (using `erlang:22-alpine` docker image). After starting the bot, I will see `websocket disconnected with reason {:remote, 1000, ""}, attempting reconnect` for several minutes, then it finally connects.

**Comment by jchristgit** [comment]
Can you reproduce this issue on the latest master?

**Comment by rikusen0335** [comment]
Currently, I don't see this issue. So this should be closed if no one has the same.

**Comment by Kraigie** [comment]
I'll close for now since I haven't seen anyone have any issues since switching to gun. 😄
