### ISSUE TITLE
Ratelimiter not handling adding reaction properly

### ISSUE THREAD

**Issue by LazyShpee** [Kraigie/nostrum#156]
Adding multiple reactions one after another gives a `%Nostrum.Error.ApiError{response: %{global: false, message: "You are being rate limited.", retry_after: 108}, status_code: 429}` instead of being queued by Nostrum.Api.Ratelimiter and handled for you.

**Comment by tmecklem** [comment]
Also seeing this. @BlindJoker want any help fixing or testing this?

**Comment by BlindJoker** [comment]
I was running the commit on my bot for a while to see if anything would explode, but I ended up forgetting about it. Everything seems to be working alright -- haven't gotten any 429s, even while spamming pagination emojis -- so I made the PR.

Thanks for the ping.

**Comment by jchristgit** [comment]
It seems this is an intended feature:tm:!

https://discord.com/developers/docs/topics/rate-limits

> Routes for controlling emojis do not follow the normal rate limit conventions. These routes are specifically limited on a per-guild basis to prevent abuse. This means that the quota returned by our APIs may be inaccurate, and you may encounter 429s.
