### ISSUE TITLE
Nostrum.Api.leave_guild/1 fails with 400: Bad Request

### ISSUE THREAD

**Issue by Meow** [Kraigie/nostrum#164]
`Nostrum.Api.leave_guild/1` fails to leave the guild, no matter what the argument passed is (string / integer).

**Expected Behavior:**
```elixir
Nostrum.Api.leave_guild(guild_snowflake)
```
would leave the guild as specified by the `guild_snowflake` variable.

**Actual Behavior:**
Fails with `400: Bad Request` response, according to the error inspection.

Here is the actual code of the command in my own bot:
```elixir
  def handle(msg, _, %Arguments{parsed: args}) do
    guild_id =
      args
      |> Enum.at(0)

    case Api.leave_guild(guild_id) do
      {:ok} ->
        Api.create_message(
          msg.channel_id,
          "I left the following guild: #{guild_id |> to_string()}"
        )

      {:error, err} ->
        Api.create_message(
          msg.channel_id,
          "Failed to leave guild: '#{guild_id |> to_string()}'\n#{err.response.message}"
        )
    end
  end
```
(`args` is a list of strings)

Converting the string to integer via `String.to_integer/1` does not yield any different results.

The same function (which calls the same API endpoint) in discord.py library (which I used to verify it was not a Discord issue), on the other hand, does work as expected.

**Comment by Andris0** [comment]
Fixed with 401443001bc2ca6227d8d189dad72400b80ffdf7.
