### ISSUE TITLE
Changing guild supervisor to use DynamicSupervisor

### ISSUE THREAD

**Issue by chasekaylee** [Kraigie/nostrum#168]
Currently Nostrum.Cache.Guild.GuildSupervisor is using deprecated :simple_one_for_one strategy. I propose a change to refactor Supervisor use  the Dynamic Supervisor :one_for_one to get rid of current warnings

**Comment by Kraigie** [comment]
Should be fixed with 6cf5637626b65b5fe3d2d630d7cec3ecbbaf229d, thanks for the report!

**Comment by chasekaylee** [comment]
@Kraigie Ahhh sweet! Didn't see that 👍 ! Any plans for a stable release soon?
