### ISSUE TITLE
SSL: :cipher: ssl_alert.erl:88:Fatal error: bad record mac

### ISSUE THREAD

**Issue by rekyuu** [Kraigie/nostrum#19]
I'm not sure there is much you can do about this, or if some hex package needs updating, but after upgrading to OpenSSL v1.1.0f I have been unable to start a nostrum bot. Here is a log of what it looks like when I attempt to start:

```
$ iex -S mix
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

14:42:25.005 [error] SSL: :cipher: ssl_alert.erl:88:Fatal error: bad record mac


14:41:22.743 [error] SSL: :cipher: ssl_alert.erl:88:Fatal error: bad record mac


14:41:22.767 [error] SSL: :cipher: ssl_alert.erl:88:Fatal error: bad record mac


14:41:22.794 [error] SSL: :cipher: ssl_alert.erl:88:Fatal error: bad record mac


14:41:22.815 [error] SSL: :cipher: ssl_alert.erl:88:Fatal error: bad record mac


14:41:22.831 [info]  Application nostrum exited: Nostrum.start(:normal, []) returned an error: shutdown: failed to start child: Nostrum.Shard.Supervisor
    ** (EXIT) shutdown: failed to start child: 0
        ** (EXIT) shutdown: failed to start child: Nostrum.Shard.Session
            ** (EXIT) normal

14:41:22.831 [info]  Application gun exited: :stopped

14:41:22.831 [info]  Application ranch exited: :stopped

14:41:22.831 [info]  Application cowlib exited: :stopped

14:41:22.831 [info]  Application httpoison exited: :stopped

14:41:22.831 [info]  Application hackney exited: :stopped

14:41:22.831 [info]  Application metrics exited: :stopped

14:41:22.831 [info]  Application ssl_verify_fun exited: :stopped

14:41:22.831 [info]  Application certifi exited: :stopped

14:41:22.831 [info]  Application mimerl exited: :stopped

14:41:22.831 [info]  Application idna exited: :stopped

14:41:22.831 [info]  Application poison exited: :stopped

14:41:22.831 [info]  Application gen_stage exited: :stopped

=INFO REPORT==== 19-Jul-2017::14:41:22 ===
    application: logger
    exited: stopped
    type: temporary
** (Mix) Could not start application nostrum: Nostrum.start(:normal, []) returned an error: shutdown: failed to start child: Nostrum.Shard.Supervisor
    ** (EXIT) shutdown: failed to start child: 0
        ** (EXIT) shutdown: failed to start child: Nostrum.Shard.Session
            ** (EXIT) normal
```

Again, I've not really seen anything like this so I have no idea if this is an issue I created during the update to v1.1.0f or not. Any insight will be wonderful.

You can see the source of my code here: https://github.com/KumaKaiNi/discord-kuma

Thank you!

**Comment by Kraigie** [comment]
I see you're on OTP 20. Were you able to launch the bot on OTP 20 before the update? Also, is your lock file up to date in the included repository? It seems to be missing some dependencies.

It does look like OTP 20 supports OpenSSL 1.1, so that's not an issue. AFAIK OTP 20 will not work with the current version of the Gun websocket dependency since its Cowlib dependency is using a deprecated crypto method. There's a Cowlib 2.0 rc that came out 7 days ago so when that is released and gun is updated on hex this should be resolved.

In the meantime you can try downgrading to OTP 19.

**Comment by rekyuu** [comment]
I've pushed the latest mix.lock, and it works on OTP 19. I'll use that for the time being. Thank you for the help!
