### ISSUE TITLE
Unhandled websocket message after application start

### ISSUE THREAD

**Issue by ndac-todoroki** [Kraigie/nostrum#21]
Version: github

Starting the application from iex -S mix (I used both the [simple](https://github.com/Kraigie/nostrum/blob/a655b8bea1c96777ea6ec729493625b147899081/examples/event_consumer.ex) and [the more complex](https://github.com/Kraigie/mark-hoff) samples), it shows the following warning.
```
16:04:21.780 [warn]  Unhandled websocket message: {:DOWN, #Reference<0.436806687.830210049.7920>, 
:process, #PID<0.242.0>, {:undef, [{:crypto, :rand_bytes, [16], []}, {:cow_ws, :key, 0, 
[file: 'src/cow_ws.erl', line: 63]}, {:gun_http, :ws_upgrade, 7, [file: 'src/gun_http.erl', line: 407]}, 
{:gun, :loop, 1, [file: 'src/gun.erl', line: 629]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}}
```
This warning comes from [here](https://github.com/Kraigie/nostrum/blob/master/lib/nostrum/shard/session.ex#L138-L141), and it does nothing, and so (or maybe not) it never connects.

When I edited the source to do the same thing as [this pattern](https://github.com/Kraigie/nostrum/blob/master/lib/nostrum/shard/session.ex#L110-L114), it keeps on doing the reconnection and never succeeds.

```
16:28:28.656 [warn]  websocket caller received DOWN, attempting reconnect

16:28:28.656 [debug] WAITING 5454 BEFORE NEXT SHARD CONNECT

16:28:34.154 [warn]  websocket caller received DOWN, attempting reconnect

16:28:34.154 [debug] WAITING 5460 BEFORE NEXT SHARD CONNECT

...
```

This is curious because the hex version will succeed with no warnings.

**Comment by PixeLInc** [comment]
For future people who see this, you no longer have to down-grade.
Until nostrum updates their dependencies, you can use the latest gun library from git and the error is gone since it supports OTP 20.

You can do this by adding
{:gun, git: "https://github.com/ninenines/gun.git", override: true},
to your deps section of mix.exs

**Comment by Kraigie** [comment]
Thanks for the find! I [added a bit to the read me](https://github.com/Kraigie/nostrum/commit/c14f97e63329f0eb3f18bf54ee87ed42ba2ba27b) to point this out until 2.0 is released.
