### ISSUE TITLE
Crazy idea: Make voice dependencies optional

### ISSUE THREAD

**Issue by jchristgit** [Kraigie/nostrum#215]
- Add `optional: true` in `mix.exs`
- Voice users need to include voice dependencies in addition to existing dependencies

Would be happy to hear feedback here.

**Comment by jb3** [comment]
Thoughts on this @Kraigie?

<img width="428" alt="Screenshot 2021-01-08 at 13 38 12" src="https://user-images.githubusercontent.com/20439493/104021495-c2db9400-51b6-11eb-994b-4f4bc5d0bbd1.png">
<img width="566" alt="Screenshot 2021-01-08 at 13 37 38" src="https://user-images.githubusercontent.com/20439493/104021448-af302d80-51b6-11eb-8f9d-f1317cdfe7e3.png">

@jchristgit seems to like it:
<img width="89" alt="Screenshot 2021-01-08 at 13 38 29" src="https://user-images.githubusercontent.com/20439493/104021511-cbcc6580-51b6-11eb-82eb-9cd4c6a49c79.png">

**Comment by BrandtHill** [comment]
Craizy

**Comment by Kraigie** [comment]
I'm okay with either approach. It seems like the more idiomatic approach would be to make them optional in the dependency but 🤷

**Comment by bbhoss** [comment]
Just looking into voice myself. The API is a little opinionated, there are some situations where I'd prefer to send proxied RTP directly maybe with a little rewriting instead of being forced into the ffmpeg route. I know it would probably require the api to change, but wouldn't it be better to keep the core library just concerned with connection setup and RTP sending, leaving what's generating that actual audio to a separate package?

**Comment by Kraigie** [comment]
I think a solution that covers both would probably be the best option, right? I can't back this up with data, but I feel like the most common use case is the ffmpeg route and the implementation is frankly above most users of this library. 

I don't see why we can't just have our own processing live on top of some core connection process. How does that sound? That way users who depend on the current functionality still can, but your use case is all supported.

**Comment by BrandtHill** [comment]
I think this can be achieved by exposing the `VoiceState` struct and a few private functions in the `Voice` module that interact with it.

I assume the overwhelming majority of users aren't going to care about the implementation and just want a simple way to play audio files and youtube videos, which is provided by ffmpeg and youtube-dl.
Exposing the `VoiceState` should give an enterprising RTP ninja everything they need to send their own audio packets, including UDP socket, IP/port, RTP timestamp/sequence, encryption key, etc.

**Comment by BrandtHill** [comment]
@bbhoss Check out [the new voice features](https://kraigie.github.io/nostrum/Nostrum.Voice.html#module-voice-without-ffmpeg) to bypass ffmpeg available in master and 0.4.7 sometime soon.

**Comment by Nezteb** [comment]
[The `mix.exs` file has hanged quite a bit since this issue was created](https://github.com/Kraigie/nostrum/compare/9c07a42a469b59e371825ad14d8d0f929b4f6334...master#diff-dfa6f4ed74c90e5d4fda283d547d366586e690387289bcfd473e3fa5f9ace308). Should this close or stay open? 😄

**Comment by BrandtHill** [comment]
The need to make voice dependencies optional was probably overstated to begin with. The only voice-specific dependency now is `:kcl`. It's a 2-module library that itself depends on four other single-module libraries.

**Comment by jchristgit** [comment]
I agree with @BrandtHill. I think when this issue was made we still had porcelain and some others? Closing.

**Comment by BrandtHill** [comment]
Yes, we also had porcelain but now use erlang ports directly.
