### ISSUE TITLE
Does nostrum support the Discord gateway interface?

### ISSUE THREAD

**Issue by vegabook** [Kraigie/nostrum#219]
Wondering if this library supports the Gateway interface as your docs only seem to talk about REST. Interested as a persistent websocket might be more appropriate given the huge volumes that some channels are currently seeing. 
https://discord.com/developers/docs/topics/gateway

**Comment by BrandtHill** [comment]
Nostrum supports the gateway interface.

**Comment by Kraigie** [comment]
For more information you can check out [this](https://kraigie.github.io/nostrum/Nostrum.Consumer.html#content) module!

For a broader overview you can check [this](https://kraigie.github.io/nostrum/events.html) out as well.
