### ISSUE TITLE
Error on multiple create_reaction: "You are being rate limited"

### ISSUE THREAD

**Issue by Neptius** [Kraigie/nostrum#234]
Hello,

I would like to add several reactions to an embed message that I will have created just before in order to create interactions.
But, by following the creation as below, all are not created and I receive: You are being rate limited.

```elixir
Nostrum.Api.create_reaction(123123123123, 321321321321, emoji1)
Nostrum.Api.create_reaction(123123123123, 321321321321, emoji2)
Nostrum.Api.create_reaction(123123123123, 321321321321, emoji3)
#...
```

Is my way of creating them wrong? Is there another method?

Thank you!

**Comment by BrandtHill** [comment]
#156
