### ISSUE TITLE
Parse Interactions Options to Integers

### ISSUE THREAD

**Issue by rushsteve1** [Kraigie/nostrum#235]
Values 6, 7, and 8 of [`ApplicationCommandOptionType`](https://discord.com/developers/docs/interactions/slash-commands#applicationcommandoptiontype) represent integer IDs and should be parsed to integers instead of being left as strings. This would cause it to match the other ID fields in the `Interaction` struct, and make working with interactions easier.

**Comment by jchristgit** [comment]
Same issue: I've tested a bit together with the `BOOLEAN` interaction type - which yields a `true` / `false` here, whilst it's currently documented to always be a `String.t()` or `nil`.
