### ISSUE TITLE
Update (or relax) dependencies

### ISSUE THREAD

**Issue by thiagomajesk** [Kraigie/nostrum#236]
Hello everyone! Just tried the lib today by creating a brand new Phoenix app and I got the following error:

```
Failed to use "cowlib" (version 2.9.1) because
  cowboy (version 2.8.0) requires ~> 2.9.1
  gun (versions 1.3.0 to 1.3.2) requires ~> 2.6.0
  mix.lock specifies 2.9.1


Failed to use "cowlib" (version 2.9.1) because
  cowboy (version 2.8.0) requires ~> 2.9.1
  gun (version 1.3.3) requires ~> 2.7.0
  mix.lock specifies 2.9.1
```

Do you think we could have this updated?
 
PS.: Out of curiosity: Is the `gun` lib really necessary if using `httpoison`?

**Comment by Kraigie** [comment]
You can override the dependencies if you wanted, but I agree that they should be updated.

Also, we use `gun` as a websocket client. I think the better question is why we `httpoison` when we use `gun`. I think they fulfill different enough roles to both be useful.

**Comment by thiagomajesk** [comment]
Hi @Kraigie! Thanks for the reply...
 
I've tried `{:nostrum, "~> 0.4", override: true}` and `{:plug_cowboy, "~> 2.0", override: true}` before posting (for test sake), but I got the same error, any suggestions?

> Also, we use gun as a websocket client. I think the better question is why we httpoison when we use gun. I think they fulfill different enough roles to both be useful.

I was curious because I thought that `httpoison` could handle WebSockets too. Thanks for the response though.

**Comment by Kraigie** [comment]
> I've tried {:nostrum, "~> 0.4", override: true} and {:plug_cowboy, "~> 2.0", override: true} before posting (for test sake), but I got the same error, any suggestions?

I think you might need to override gun, but I never remember these things. Regardless it'll be updated soon!

> I was curious because I thought that httpoison could handle WebSockets too. Thanks for the response though.

It's an HTTP library so we probably could have it handle websockets, but gun was built in a way that makes it very easy to integrate with.

**Comment by thiagomajesk** [comment]
> I think you might need to override gun, but I never remember these things. 

Yes, of course! I was already trying to figure out if I ever manage to override an "indirect" dependency of some project 😆. 
I manage to compile with `gun`'s master, but also overriding `cowlib` since they're requiring `cowlib` 1.10 for the new rc's:

```
 {:gun, github: "ninenines/gun", override: true},
 {:cowlib, "~> 2.10", override: true}
```

At least it's compiling now! 🙏

> Regardless it'll be updated soon!

Sorry to bother you, but do you have any ETA to share?

> It's an HTTP library so we probably could have it handle websockets, but gun was built in a way that makes it very easy to integrate with.

Interesting, I haven't heard about `gun` before, but I'll certainly take a look at it. Thanks for the clarification.

**Comment by thiagomajesk** [comment]
I can confirm this fixed the problem for me. Thanks for the great work @jchristgit! Cheers!
