### ISSUE TITLE
Fetching Guild from GuildCache not working with enabled intents

### ISSUE THREAD

**Issue by ramadan8** [Kraigie/nostrum#256]
command.ex
```elixir
...

guild = GuildCache.get!(msg.guild_id)
Enum.each(guild.members, fn {_id, member} -> IO.puts member.user.username end)

...
```

config.exs
```elixir
config :nostrum,
  token: System.get_env("DISCORD_TOKEN"),
  num_shards: :auto,
  gateway_intents: [
    :guilds,
    :guild_messages,
    :guild_members,
    :guild_message_reactions
  ]
```

Although I've enabled the privileged intent for guild members in the Discord Developer panel and added the intents to my config it still only finds my bot's user when printing out the members from GuildCache.

**Comment by PixeLInc** [comment]
Heyo, It seems that you must _also_ enable the GUILD_PRESENCES privileged intent in order to enumerate all members of a guild.
So if you could try enabling both `GUILD_PRESENCES` and `GUILD_MEMBERS` and see if that fixes the issue for you!

**Comment by ramadan8** [comment]
> Heyo, It seems that you must _also_ enable the GUILD_PRESENCES privileged intent in order to enumerate all members of a guild.
> So if you could try enabling both `GUILD_PRESENCES` and `GUILD_MEMBERS` and see if that fixes the issue for you!

Seems that enabling `GUILD_PRESENCES` *and* adding it to my config has done the trick. Thank you!
