### ISSUE TITLE
Edit permissions for slash commands

### ISSUE THREAD

**Issue by jkbbwr** [Kraigie/nostrum#287]
Editing the permissions for slash commands seems to be missing, I can take a crack at doing this myself but it will take a bit to get upto speed.

https://discord.com/developers/docs/interactions/slash-commands#get-guild-application-command-permissions

**Comment by jchristgit** [comment]
Hi @jkbbwr, if you want to take a stab at this, that would be great! I can maybe take a look sometime this weekend but I can't make any guarantees. Just tell me if you want to work it and I will assign you 🙂
