### ISSUE TITLE
Does this library support the new buttons?

### ISSUE THREAD

**Issue by beep-beep-beep-boop** [Kraigie/nostrum#292]
title, https://support.discord.com/hc/en-us/articles/1500012250861-Bots-Buttons

**Comment by Th3-M4jor** [comment]
Yes it does, you'll have to handle them in a somewhat lower level format by following the Discord API docs at https://discord.com/developers/docs/interactions/message-components

But Nostrum has full support for them.

**Comment by jchristgit** [comment]
Yes, there's currently no abstraction over them or anything. @beep-beep-beep-boop did you have anything in mind we could build here to make working with the measier?

**Comment by bdanklin** [comment]
Potentially resolved with #307

**Comment by jb3** [comment]
This is now resolved after the Components PR, #373, features are found [here](https://kraigie.github.io/nostrum/Nostrum.Struct.Component.html)
