### ISSUE TITLE
Stream playback support

### ISSUE THREAD

**Issue by HATRED-arh** [Kraigie/nostrum#297]
Hello!
I might be wrong, but it seems that Nostrum currently doesn't support stream playback. 
Are there plans for this in the future? Would be nice to play some 24/7 radios or something. 

At the moment if I try to pass stream link into Voice.play() I get `ERROR: requested format not available`
If I change youtube-dl arguments in **audio.ex** file to `["-f", "bestaudio/best"], ["-o", "-"],  ["-q"], [url]`, it will process stream link and play it for several seconds. 
I know it's not a fix, since it still writes to file and eventually timeouts.  
Is it possible to implement function like Voice.play_stream() or something alike?

**Comment by HATRED-arh** [comment]
> Can you provide an example URL you're trying to play?

Sure: 
https://youtu.be/oHY1RpbKDDA
https://youtu.be/LN4r-K8ZP5Q

**Comment by BrandtHill** [comment]
I'm unable to get `youtube-dl` to download a live stream with `-f best`. It will download a 256KB segment then hang. Do you have a way to continually download ongoing streams with `youtube-dl`?

**Comment by HATRED-arh** [comment]
I did some research
You can use `youtube-dl` only to get source link and just pass it to ffmpeg
Example:
`youtube-dl -f bestaudio/best -g https://youtu.be/LN4r-K8ZP5Q`
And pass the url you just got to ffmpeg:
` ffmpeg -i https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1628849069/ei/Te8VYdbCFeWjpATmu61Q/ip/2a03:ec00:b194:2375:6192:420:b407:e034/id/LN4r-K8ZP5Q.1/itag/96/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dyes%3Bitag%3D137/hls_chunk_host/rr2---sn-ahu-gpml.googlevideo.com/playlist_duration/30/manifest_duration/30/vprv/1/playlist_type/DVR/initcwndbps/9480/mh/fp/mm/44/mn/sn-ahu-gpml/ms/lva/mv/m/mvi/2/pl/42/dover/11/keepalive/yes/fexp/24001373,24007246/mt/1628827224/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,live,sgoap,sgovp,playlist_duration,manifest_duration,vprv,playlist_type/sig/AOq0QJ8wRgIhAPGerF_AWgP_HcelW7x-tm07BQuF1bdxPHLC1cmiaFWjAiEAz804gE9de9lNV6kvtc9a4q2CbG8sMHrKpoTxqCyKxec%3D/lsparams/hls_chunk_host,initcwndbps,mh,mm,mn,ms,mv,mvi,pl/lsig/AG3C_xAwRQIhAKm8tzZfkRlk6NjMgn92tP98VThm7HCmJfMEQazhjxNMAiAKrg8O5_uZOAFdTYhFXCviQ-qKDtjzGUJA15PW_FAtxA%3D%3D/playlist/index.m3u8 -f s16le -ar 48000 -ac 2 -loglevel warning -vn pipe:1 `

**Comment by BrandtHill** [comment]
When I use `ffmpeg` for writing to a file, it writes a small portion of the stream then stops downloading from the stream and hangs. Similarly when I write to `pipe:1` it outputs momentarily then exits with an IO error.

I've also tried using `streamlink`. When writing to a file, it works as expected and continually appends to a growing file. When writing to `stdout`, it exits with an IO error.

**Comment by BrandtHill** [comment]
Actually just kidding I tried this in Nostrum and it works. `streamlink` only throws an I/O when writing to `stdout` of my console, but it's working in Nostrum. Very cool stuff... will let you know when it's up in my fork.

**Comment by jchristgit** [comment]
Fixed with #308, thanks!
