### ISSUE TITLE
Incorrect `@spec` for `Api.execute_webhook`

### ISSUE THREAD

**Issue by Th3-M4jor** [Kraigie/nostrum#302]
I noticed that the map defined in the `@spec` for [execute webook](https://github.com/kraigie/nostrum/blob/master/lib/nostrum/api.ex#L2822) is written such that all fields are required, however this is not the case.

Only one of `content`, `embeds`, or `file` are required fields.

**Comment by jchristgit** [comment]
Hmm, I see. How would we typespec this in Elixir? I'm not sure how to make "one of" work in typespecs though - lots of pipes?

**Comment by Th3-M4jor** [comment]
Lots of pipes, or perhaps marking them all as optional in the spec and in the docs state that at least one must be present?
Then in the code itself have a check for the presence of at least one otherwise raise an exception?
