### ISSUE TITLE
Update gateway version to stable

### ISSUE THREAD

**Issue by jchristgit** [Kraigie/nostrum#319]
We are currently running gateway version 6.

Per the [docs](https://discord.com/developers/docs/topics/gateway#gateways-gateway-versions), this is deprecated.

We should port this to a stable version.

**Comment by jchristgit** [comment]
Is there a changelog available for the gateway versions somewhere?

> The Discord Gateway has a versioning system separate from the HTTP APIs. The documentation herein is only for the latest version in the following table, unless otherwise specified.

**Comment by Th3-M4jor** [comment]
It should all be right here https://discord.com/developers/docs/change-log

**Comment by jchristgit** [comment]
Ah, you're right, I thought it's a separate doc. Thanks for linking!

**Comment by jchristgit** [comment]
Ah, we are using V8 in the Gateway in nostrum 0.5. We are winners.

**Comment by jchristgit** [comment]
We are using version 10 by now, see `base_route` in `Nostrum.Constants`.
