### ISSUE TITLE
Add schedule events endpoint

### ISSUE THREAD

**Issue by papey** [Kraigie/nostrum#361]
Just saw that Discord now has a ["schedule events" feature](https://support.discord.com/hc/fr/articles/4409494125719-Scheduled-Events).

I search inside the Nostrum issues/code/docs and found nothing about it (sorry if i'm wrong or if I missed something).

Let me know if you need help on this, if you have any pointers for me on how to do it properly, let's go.

Thanks a lot.

**Comment by jchristgit** [comment]
This is interesting, but from what I gathered in our development chat, this is still undocumented on Discord's side of things at the moment. I think it would be great to have support for this in Nostrum, but we should wait until Discord publicly documents this to work on this.

**Comment by jchristgit** [comment]
Sorry, ignore what I just said, the documentation was merged here: https://github.com/discord/discord-api-docs/pull/3586

**Comment by papey** [comment]
Thanks @jchristgit for the feedback. After reading the issue you mentioned, it looks like API endpoints are now usable by bots.

From what I read in the nostrum repo. I have to

- add routes in `lib/nostrum/constants.ex`
- add api endpoints in `lib/nostrum/api.ex`
- add unit tests

If it looks good, let's go :+1:

**Comment by jchristgit** [comment]
Hi @papey, yes, that sounds good. I'm not sure how far we can go with unit tests here, though, so feel free to leave these out if it ends up being messy 🙂

**Comment by papey** [comment]
Done here https://github.com/kraigie/nostrum/commit/eb02b4b560fc71c8771472e0b624daa904626539, kudos to @Th3-M4jor.
