### ISSUE TITLE
Audio timeout not being cancelled after calling `Nostrum.Voice.pause/1` and `Nostrum.Voice.resume/1`

### ISSUE THREAD

**Issue by doorgan** [Kraigie/nostrum#368]
In a barebones Nostrum(master branch) project, I'm able to consistently reproduce this issue doing the following in IEx:

```elixir
guild_id = <GUILD ID>
channel_id = <CHANNEL_ID>
url = "https://www.youtube.com/watch?v=o7fgFaXKVa0" # Serial experiments Lain opening song

alias Nostrum.Voice

Voice.join_channel(guild_id, channel_id)
Process.sleep(1000)
Voice.play(guild_id, url, :ytdl)
Process.sleep(10_000)
Voice.pause(guild_id)
Process.sleep(2000)
Voice.resume(guild_id)

```

The song will play for a while(10 seconds is enough for me to let it buffer and play for a couple of seconds), then pause, then resume and after 500ms if will stop playing.

The 500 seems to be the `:audio_timeout` option for Nostrum, according to this line:
https://github.com/Kraigie/nostrum/blob/e08d15dd18cfdeefcf1f12c63d676dbf6d5e1f0f/lib/nostrum/voice/audio.ex#L111

The troublesome code seems to be in this function:
https://github.com/Kraigie/nostrum/blob/e08d15dd18cfdeefcf1f12c63d676dbf6d5e1f0f/lib/nostrum/voice/audio.ex#L110-L125

For some reason, after a pause the timer created in line 112 is not being cancelled, so the bot stops playing. To verify this timer is the issue, I commented the call to `Proc.stop` here:
https://github.com/Kraigie/nostrum/blob/e08d15dd18cfdeefcf1f12c63d676dbf6d5e1f0f/lib/nostrum/voice/audio.ex#L310-L314
And the issue "goes away" (of course keeping the process alive in this case is surely a bug though I don't know enough to know how).

Changing the `:audio_timeout` option won't solve this. If I set it to, say, `15_000`, then the bot will resume playing and stop after 15 seconds.

**Comment by BrandtHill** [comment]
I have experienced this bug occasionally. 

The `:audio_timeout` option only affects the beginning of audio playback so it won’t change anything. 

The porcelain process must be killed as with stdin as input (the case with `:ytdl`) the ffmpeg will hang indefinitely. 

I will look into the timer issue.
