### ISSUE TITLE
Nostrum.Consumer should be generalized to allow full utilization of GenStage capabilities

### ISSUE THREAD

**Issue by aawilson** [Kraigie/nostrum#37]
Right now, the Nostrum.Consumer behaviour specifies the GenStage behaviour with the :consumer type. Ideally, it would also support the :producer_consumer type (and handle_events would in that case pass its event objects in its return value), allowing other modules using the GenStage behaviour to subscribe directly to Nostrum.Consumer (or whatever would be named under this scheme, whether that name becomes something more general and it's parameterized or whether a Nostrum.ProducerConsumer behaviour is introduced alongside it).

**Comment by Kraigie** [comment]
Very recently I added support for people to define their own consumers, which should also satisfy your use case of defining `producer_consumer`s.

See [here](https://kraigie.github.io/nostrum/consumers.html#content) for the documentation on it. 

If you had something else in mind, or want to discuss whether this should be implemented at a higher level by the lib, I'm open to have the discussion!

**Comment by aawilson** [comment]
Oh nice, `Nostrum.Util.html#producers/0` should be precisely what I need, the main thing that was making me itch when implementing my own behaviour was dealing with the registry directly. Thanks for pointing that out.

**Comment by Kraigie** [comment]
No, problem. Glad I could help!
