### ISSUE TITLE
`cowlib` failing to fetch on `mix deps.get` when adding nostrum as dependency

### ISSUE THREAD

**Issue by nunobernardes99** [Kraigie/nostrum#424]
### Description
Creating a new phoenix project, when adding nostrum as a dependency and running `mix deps.get` it fails to fetch `cowlib`.

### Versions
Elixir: `1.13.4`
Erlang: `24.3.4`

### Error
```
* Getting cowlib (Hex package)
** (exit) exited in: GenServer.call(:hex_fetcher, {:await, {:tarball, "hexpm", "cowlib", "2.11.1"}}, 120000)
    ** (EXIT) time out
    (elixir 1.13.4) lib/gen_server.ex:1030: GenServer.call/3
    (hex 1.0.1) lib/hex/scm.ex:128: Hex.SCM.update/1
    (hex 1.0.1) lib/hex/scm.ex:231: Hex.SCM.checkout/1
    (mix 1.13.4) lib/mix/dep/fetcher.ex:64: Mix.Dep.Fetcher.do_fetch/3
    (mix 1.13.4) lib/mix/dep/converger.ex:190: Mix.Dep.Converger.all/9
    (mix 1.13.4) lib/mix/dep/converger.ex:201: Mix.Dep.Converger.all/9
    (mix 1.13.4) lib/mix/dep/converger.ex:123: Mix.Dep.Converger.all/7
    (mix 1.13.4) lib/mix/dep/converger.ex:108: Mix.Dep.Converger.all/4
```

**Comment by Th3-M4jor** [comment]
You're probably going to have to override the cowlib version because the one used by phoenix is older than what nostrum uses `{:cowlib, "~> 2.11", hex: :remedy_cowlib, override: true}`

**Comment by jchristgit** [comment]
Closing here since the `remedy_cowlib` fork should fix the issue. Feel free to reopen if it doesn't work as expected.

**Comment by plicjo** [comment]
@jchristgit Nosedrum fails to install for me due to this problem. I think it also needs this override.

**Comment by bdanklin** [comment]
> @jchristgit Nosedrum fails to install for me due to this problem. I think it also needs this override.

Libraries cannot set overrides. it is up to the end user.
