### ISSUE TITLE
Feat: pass shard list to gateway

### ISSUE THREAD

**Issue by mymindishazel** [Kraigie/nostrum#445]
Currently, [Nostrum launches all shards when given a shard count](https://github.com/Kraigie/nostrum/blob/master/lib/nostrum/shard/supervisor.ex#L78).
For very large bots, it's not feasible to run all shards on one machine.
To solve this, you could pass a list of shards for nostrum to launch on each machine, instead of it launching all shards up to the shard count.

I'm not that familiar with large scale Erlang, but would the best option here be to allow a list of shards to be passed in, or is there another way to scale a nostrum deployment to multiple machines?

**Comment by jchristgit** [comment]
For a start we will provide a configuration setting to select specific shards to start up, and functions to start / stop shards under the shard supervisor at runtime. I think we're still a bit away from multi-node (caches, rest ratelimiter, gateway ratelimiting), but that said, installing something like [horde](https://github.com/derekkraan/horde) and using one of its distributed supervisors on the shard supervisor should allow automatic distribution of shards over connected nodes.

**Comment by jchristgit** [comment]
I made a PR here https://github.com/Kraigie/nostrum/pull/497 which adds support for passing a range of shards. There have also been a fair number of patches towards allowing nostrum to run on multiple machines (though it isn't fully implemented _yet_). Is that what you had in mind?

**Comment by mymindishazel** [comment]
First of all, hat off to you for replying to a half-year-old issue.
Secondly, yes! That seems like what I was thinking.

I don't know if I'm seeing this correctly though, but https://github.com/Kraigie/nostrum/blob/configurable-shards/lib/nostrum/shard/payload.ex#L27 is pulling the num_shards part of the payload from the highest one in the range, which means the only actual possible range would be 0..num_shards, because if i e.g. hand two nostrum instances 0..1 and 2..3, the first one will misreport the total shard count as being 1

**Comment by jchristgit** [comment]
> First of all, hat off to you for replying to a half-year-old issue.

Better late than never 🙂 

> I don't know if I'm seeing this correctly though, but https://github.com/Kraigie/nostrum/blob/configurable-shards/lib/nostrum/shard/payload.ex#L27 is pulling the num_shards part of the payload from the highest one in the range, which means the only actual possible range would be 0..num_shards, because if i e.g. hand two nostrum instances 0..1 and 2..3, the first one will misreport the total shard count as being 1

Hmm yes, you are right. I think to fix this we need to introduce a new configuration variable, `highest_shard_num`, for this purpose exactly 🤔

**Comment by mymindishazel** [comment]
Maybe the current one could be overloaded to work as is and with a tuple of {ids, total}?
