### ISSUE TITLE
Add kick support.

### ISSUE THREAD

**Issue by shymega** [Kraigie/nostrum#47]
Currently, to the best of my knowledge, Nostrum doesn't support kicking a user from a guild. It supports banning however.

Could kick support be added to the roadmap for addition to Nostrum, or is there a limitation of Discord's API with regards to kicking a user?

Thanks :smile:

**Comment by Kraigie** [comment]
This currently exists, docs are [here]( https://kraigie.github.io/nostrum/Nostrum.Api.html#remove_member/2), but apparently it only works on `memebers`s. Luckily those'll be the ones you want out of your guild. 🙃

**Comment by shymega** [comment]
Oh man, I feel like an idiot. I'm primarily an IRC user, so I searched the docs for a `kick_member` fun, sorry for opening an issue!

Thanks for your help though!
