### ISSUE TITLE
Add support for application-commands#permissions feature

### ISSUE THREAD

**Issue by alichz2001** [Kraigie/nostrum#514]
Currently, the Nostrum module lacks support for the application-commands#permissions feature in Discord APIs. This feature is essential for managing user permissions and access levels to application commands.

I would like to request the addition of this feature to the Nostrum module. It would greatly enhance the functionality and flexibility of the module, allowing developers to control and customize permissions for application commands in Discord.

If this feature is already supported and I have overlooked it, please provide guidance on how to use it. Otherwise, I would appreciate it if the development team could consider adding this feature to the roadmap for future updates.

Thank you for your attention to this matter.

https://discord.com/developers/docs/interactions/application-commands#permissions

**Comment by Th3-M4jor** [comment]
Looks like Nostrum does already support this, see [`edit_application_command_permissions/4`](https://kraigie.github.io/nostrum/Nostrum.Api.html#edit_application_command_permissions/4)

**Comment by alichz2001** [comment]
Thank you for your response and assistance!
