### ISSUE TITLE
Is there TextInput Modal works? Any example?

### ISSUE THREAD

**Issue by Bogdan1001** [Kraigie/nostrum#518]
Hey,

In the doc I can't get how to send modal messages. I've tried a few ways but no one works, is the Lib support it? Can you show me code please :)

**Comment by GeordieP** [comment]
I was also having trouble getting modals to work, seeing some confusing error messages from the Discord API. I've got it working now, so here's a short example for anyone else struggling!

1. First, we need something to trigger the modal. I'll use a message with a button component for this example, but it could probably be a slash command instead; the important thing is the `custom_id`, which I'll set to `MODALS_EXAMPLE_123`.

```ex
{:ok, _message} =
  Nostrum.Api.create_message(channel_id,
    content: "Click the button below to open a modal",
    components: [
      Nostrum.Struct.Component.ActionRow.action_row(
        components: [
          Nostrum.Struct.Component.Button.interaction_button(
            "Click me!",
            "MODALS_EXAMPLE_123",
            style: Nostrum.Constants.ButtonStyle.primary()
          )
        ]
      )
    ]
  )
```

2. Next we'll handle the button's `INTERACTION_CREATE` event, matching on that `custom_id` value `MODALS_EXAMPLE_123`. We'll receive this event when a user clicks the button, and we'll respond with an interaction response containing modal components.

The TextInput component has a custom ID parameter of `MODALS_EXAMPLE_TEXTINPUT_123`. That's useful for pattern matching later, when we want to get the text input's value.

The modal itself has a custom ID parameter of `MODALS_EXAMPLE_SUBMIT_123`, which we'll receive when the modal form is submitted.

```ex
def handle_event(
      {:INTERACTION_CREATE,
        %Nostrum.Struct.Interaction{
          data: %Nostrum.Struct.ApplicationCommandInteractionData{
            custom_id: "MODALS_EXAMPLE_123"
          }
        } = interaction, _ws_state}
    ) do
  modal_action_row =
    Nostrum.Struct.Component.ActionRow.action_row(
      components: [
        Nostrum.Struct.Component.TextInput.text_input(
          "Title here",
          "MODALS_EXAMPLE_TEXTINPUT_123"
        )
      ]
    )

  Nostrum.Api.create_interaction_response(interaction, %{
    # type 9 = MODAL https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-response-object-interaction-callback-type
    type: 9,
    data: %{
      title: "Example modal title",
      custom_id: "MODALS_EXAMPLE_SUBMIT_123",
      components: [modal_action_row]
    }
  })
end
```

NOTE: All of the parameters shown in that interaction response `data` map are required! If `title` or `custom_id` or `components` are missing, the Discord API returns an error message like this:

```ex
{:error, %Nostrum.Error.ApiError{status_code: 400, response: %{code: 50035, message: "Invalid Form Body", errors: %{data: %{title: %{_errors: [%{code: "BASE_TYPE_REQUIRED", message: "This field is required"}]}}}}}}
```

3. Last, we'll handle the form submit's `INTERACTION_CREATE` event, matching on that custom ID of `MODALS_EXAMPLE_SUBMIT_123`.

Notice that we can pattern match on the TextInput's custom ID `MODALS_EXAMPLE_TEXTINPUT_123` when we're extracting the value. Useful for knowing which input some data is coming from when there are more than one in a form, no matter the order they're in.

```ex
def handle_event(
      {:INTERACTION_CREATE,
        %Nostrum.Struct.Interaction{
          data: %Nostrum.Struct.ApplicationCommandInteractionData{
            custom_id: "MODALS_EXAMPLE_SUBMIT_123"
          }
        } = interaction, _ws_state}
    ) do
  # handle the form submit here
  IO.inspect(interaction)

  # naively matching the TextInput value to extract user's input..
  %{data: %{components: [%{components: [%{
      custom_id: "MODALS_EXAMPLE_TEXTINPUT_123", value: value_from_text_input}
    ]}]}
  } = interaction

  IO.puts("The user submitted: '#{value_from_text_input}'")

  # respond to the interaction so Discord doesn't show an error
  # I'm not really sure if 6 is the right type for a modal response, but it works
  Nostrum.Api.create_interaction_response(interaction, %{
    # type 6 = DEFERRED_UPDATE_MESSAGE https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-response-object-interaction-callback-type
    type: 6
  })
end
```

**Comment by jb3** [comment]
Thanks for the code examples! I will see if we can get another docs page that goes over basics of components and responding to interactions :smile:
