### ISSUE TITLE
ChannelCache documentation enhancements

### ISSUE THREAD

**Issue by jb3** [Kraigie/nostrum#537]
Whilst it is mentioned in the documentation that the `ChannelCache` only stores `DMChannels`, I think we should make this more clear to the user, my proposals are:

- We rename this structure to `DMChannelCache`, as it is not a generic channel cache
- We add a warning to the docs instead of just having this feature in the blurb

This is based off the fact that several users in the nostrum channel have been confused by this behavior, including myself at first. We did change this behavior and as such I think we should make it as clear as possible that this is how it works. At the very least, if users get errors about the ChannelCache module rename it should prompt them to check they are actually using it as intended.

We could also include a code sample like the following on how to get a `GuildChannel`:

```elixir
iex(20)> channel_id = 1229955694258684005
1229955694258684005
iex(21)> guild_id = Nostrum.Cache.ChannelGuildMapping.get(channel_id)
1226944827137069107
iex(22)> {:ok, guild} = Nostrum.Cache.GuildCache.get(guild_id)
{:ok,
 %Nostrum.Struct.Guild{
   id: 1226944827137069107,
   name: "nostrum test",
   ...
 }}
iex(24)> guild.channels[channel_id].name
"test"
```

**Comment by jchristgit** [comment]
This sounds good to me.

One alternative: we split the guild channels out of the guild struct and incorporate them into the channel cache. I don't think this makes much sense though, because to my knowledge guild channels have a lot of attributes that regular channels do not.
