### ISSUE TITLE
Voice state updates not handled

### ISSUE THREAD

**Issue by Kraigie** [Kraigie/nostrum#84]
While the lib doesn't currently support voice, it would still be proper to handle voice state updates. The logic to do so should be [here](https://github.com/Kraigie/nostrum/blob/master/lib/nostrum/shard/dispatch.ex#L212), and the docs for it are [here](https://discordapp.com/developers/docs/topics/gateway#voice-state-update).

The voice server update event should also probably be implemented. And is located nearby the referenced material. 

This would close #26 and #22 I guess. 🙃

**Comment by BrandtHill** [comment]
Out of necessity, I handle voice state updates in #180 while implementing voice. They remain a list of flat maps in the guild cache. I believe it obsoletes the 3yo PR #22.
