### ISSUE TITLE
Support uploading StringIO objects

### ISSUE THREAD

**Issue by jchristgit** [Kraigie/nostrum#86]
[`Api.create_message/2`](https://kraigie.github.io/nostrum/Nostrum.Api.html#create_message/2)s `:file` parameter currently only supports a file specified with an explicit path. Being able to send `StringIO`s in addition to regular files would be great.

**Comment by Kraigie** [comment]
Added support for this with 2ff47a08c0dd1ec24b7ef4172b540691012a6d4a.

Thanks for bringing up this issue!
