### ISSUE TITLE
Implement Snowflake.from_time

### ISSUE THREAD

**Issue by z64** [Kraigie/nostrum#89]
Generating snowflake values has a few use cases:

- Fetching channel history before/after/around a certain time, when an existing message ID isn't known
- Filtering messages out of a collection older than two weeks for bulk deletion
- If search is ever exposed to bots, the search API uses snowflakes as well for its time filters
- For sending `nonce` in creating messages

**Comment by Kraigie** [comment]
Implemented with #90
